#!/usr/bin/env ruby
require 'open-uri'
require 'active_support'
require 'active_support/core_ext'

monsters_en = {
  # Mamel
  マムル: 'Mamel',
  あなぐらマムル: 'Pit Mamel',
  洞窟マムル: 'Cave Mamel',
  ギタンマムル: 'Gitan Mamel',
  闇マムル: 'Dark Mamel',
  闇あなぐらマムル: 'Dark Pit Mamel',
  闇洞窟マムル: 'Dark Cave Mamel',
  闇ギタンマムル: 'Dark Gitan Mamel',
  # Sproutant
  おばけカイワレ: 'Sproutant',
  カイワレ入道: 'Sproutyrant',
  カイワレ魔王: 'Sprouterror',
  カイワレ大魔王: 'Sproutitan',
  夜おばけカイワレ: 'Vile Sproutant',
  夜カイワレ入道: 'Vile Sproutyrant',
  夜カイワレ魔王: 'Vile Sprouterror',
  夜カイワレ大魔王: 'Vile Sproutitan',
  # Colum
  コロン: 'Colum',
  コロロン: 'Cololum',
  コロコロン: 'Colocolum',
  コロコロコロン: 'Colocolocolum',
  悪コロン: 'Bad Colum',
  悪コロロン: 'Bad Cololum',
  悪コロコロン: 'Bad Colocolum',
  悪コロコロコロン: 'Bad Colocolocolum',
  # Seedie
  タネッコ: 'Seedie',
  アズキッコ: 'Beanie',
  ナッツッコ: 'Nuttie',
  ダイズッコ: 'Grainie',
  ダークタネッコ: 'Hateful Seedie',
  ダークアズキッコ: 'Hateful Beanie',
  ダークナッツッコ: 'Hateful Nuttie',
  ダークダイズッコ: 'Hateful Grainie',
  # Chintala
  チンタラ: 'Chintala',
  中チンタラ: 'Mid Chintala',
  大チンタラ: 'Big Chintala',
  特大チンタラ: 'Huge Chintala',
  悪チンタラ: 'Evil Chintala',
  悪中チンタラ: 'Evil Mid Chintala',
  悪大チンタラ: 'Evil Big Chintala',
  悪特大チンタラ: 'Evil Huge Chintala',
  # Grass Boy
  草子どり: 'Grass Boy',
  草兄どり: 'Grass Bro',
  草親どり: 'Grass Guy',
  草老いどり: 'Grass Gramps',
  黒草子どり: 'Dark Grass Boy',
  黒草兄どり: 'Dark Grass Bro',
  黒草親どり: 'Dark Grass Guy',
  黒草老いどり: 'Dark Grass Gramps',
  # Pin Kid
  針子どり: 'Pin Kid',
  針兄どり: 'Pin Dude',
  針親どり: 'Pin Poppa',
  針老いどり: 'Pin Gramps',
  黒針子どり: 'Foul Pin Kid',
  黒針兄どり: 'Foul Pin Dude',
  黒針親どり: 'Foul Pin Poppa',
  黒針老いどり: 'Foul Pin Gramps',
  # Sweet Nut
  あまぐりん: 'Sweet Nut',
  しぶぐりん: 'Acrid Nut',
  からぐりん: 'Spicy Nut',
  にがぐりん: 'Bitter Nut',
  腐りあまぐりん: 'Putrid Sweet Nut',
  腐りしぶぐりん: 'Putrid Acrid Nut',
  腐りからぐりん: 'Putrid Spicy Nut',
  腐りにがぐりん: 'Putrid Bitter Nut',
  # Blade Bee
  コガタナバチ: 'Blade Bee',
  ワキザシバチ: 'Dagger Bee',
  カタナバチ: 'Katana Bee',
  ダイトウバチ: 'Zanbeeto',
  闇コガタナバチ: 'Dark Blade Bee',
  闇ワキザシバチ: 'Dark Dagger Bee',
  闇カタナバチ: 'Dark Katana Bee',
  闇ダイトウバチ: 'Dark Zanbeeto',
  # Nigiri Baby
  にぎり見習い: 'Nigiri Baby',
  にぎり変化: 'Nigiri Morph',
  にぎり親方: 'Nigiri Boss',
  にぎり元締: 'Nigiri King',
  腐りにぎり見習い: 'Foul Nigiri Baby',
  腐りにぎり変化: 'Foul Nigiri Morph',
  腐りにぎり親方: 'Foul Nigiri Boss',
  腐りにぎり元締: 'Foul Nigiri King',
  # Froggo
  ガマラ: 'Froggo',
  ガマグッチ: 'Froggucci',
  ガマゴン: 'Froggon',
  ガマドーン: 'Kleptoad',
  腹黒ガマラ: 'Snide Froggo',
  腹黒ガマグッチ: 'Snide Froggucci',
  腹黒ガマゴン: 'Snide Froggon',
  腹黒ガマドーン: 'Snide Kleptoad',
  # Karakuroid
  カラクロイド: 'Karakuroid',
  スチームロイド: 'Steamroid',
  エレキロイド: 'Electroid',
  バイオロイド: 'Cyberoid',
  闇カラクロイド: 'Dark Karakuroid',
  闇スチームロイド: 'Dark Steamroid',
  闇エレキロイド: 'Dark Electroid',
  闇バイオロイド: 'Dark Cyberoid',
  # Tiger Tosser
  タイガーウッホ: 'Tiger Tosser',
  タイガーウホホ: 'Tiger Hurler',
  タイガーウホーン: 'Tiger Chucker',
  タイガーウボッホ: 'Tiger Ace',
  ダークウッホ: 'Dark Tosser',
  ダークウホホ: 'Dark Hurler',
  ダークウホーン: 'Dark Chucker',
  ダークウボッホ: 'Dark Ace',
  # Curse Girl
  ノロージョ: 'Curse Girl',
  ノロージョの姉: 'Cursister',
  ノロージョの母: 'Curspinster',
  ノロージョの婆: 'Cursenior',
  闇ノロージョ: 'Foul Curse Girl',
  闇ノロージョの姉: 'Foul Cursister',
  闇ノロージョの母: 'Foul Curspinster',
  闇ノロージョの婆: 'Foul Cursenior',
  # Fearabbit
  フィアーラビ: 'Fearabbit',
  ホラーラビ: 'Scarabbit',
  ドレッドラビ: 'Horrabbit',
  テリブルラビ: 'Terrabbit',
  闇フィアーラビ: 'Dark Fearabbit',
  闇ホラーラビ: 'Dark Scarabbit',
  闇ドレッドラビ: 'Dark Horrabbit',
  闇テリブルラビ: 'Dark Terrabbit',
  # Gyaza
  ギャザー: 'Gyaza',
  キラーギャザー: 'Death Gyaza',
  ヘルギャザー: 'Hell Gyaza',
  フォールギャザー: 'Doom Gyaza',
  悪ギャザー: 'Evil Gyaza',
  悪キラーギャザー: 'Evil Death Gyaza',
  悪ヘルギャザー: 'Evil Hell Gyaza',
  悪フォールギャザー: 'Evil Doom Gyaza',
  # Pumphantasm
  パコレプキン: 'Pumphantasm',
  パコレプキーナ: 'Pumphantom',
  パコレプキング: 'Pumpanshee',
  パコレプゴッド: 'Pumptergeist',
  悪パコレプキン: 'Vile Pumphantasm',
  悪パコレプキーナ: 'Vile Pumphantom',
  悪パコレプキング: 'Vile Pumpanshee',
  悪パコレプゴッド: 'Vile Pumptergeist',
  # Floaty
  フワッティー: 'Floaty',
  フカッティー: 'Poofy',
  モコッティー: 'Jouncy',
  ポヨッティー: 'Bouncy',
  悪フワッティー: 'Evil Floaty',
  悪フカッティー: 'Evil Poofy',
  悪モコッティー: 'Evil Jouncy',
  悪ポヨッティー: 'Evil Bouncy',
  # N'dubba
  ンドゥバ: "N'dubba",
  ンドゥルー: "N'twyn",
  ンバマ: "N'mach",
  ンバルーン: "N'dup",
  闇ンドゥバ: "Dark N'dubba",
  闇ンドゥルー: "Dark N'twyn",
  闇ンバマ: "Dark N'mach",
  闇ンバルーン: "Dark N'dup",
  # Mixer
  マゼルン: 'Mixer',
  マゼモン: 'Mixermon',
  マゼゴン: 'Mixergon',
  マゼドン: 'Mixerdon',
  ダークマゼルン: 'Dark Mixer',
  ダークマゼモン: 'Dark Mixermon',
  ダークマゼゴン: 'Dark Mixergon',
  ダークマゼドン: 'Dark Mixerdon',
  # Scorpion
  毒サソリ: 'Scorpion',
  鬼サソリ: 'VeniScorp',
  しびれサソリ: 'StunScorp',
  劇毒サソリ: 'BlightScorp',
  ダーク毒サソリ: 'Dark Scorpion',
  ダーク鬼サソリ: 'Dark VeniScorp',
  ダークしびれサソリ: 'Dark StunScorp',
  ダーク劇毒サソリ: 'Dark BlightScorp',
  # Mutaikon
  おばけ大根: 'Mutaikon',
  めまわし大根: 'Dazikon',
  ねむり大根: 'Dozikon',
  みだれ大根: 'Mesmerikon',
  ダークおばけ大根: 'Dark Mutaikon',
  ダークめまわし大根: 'Dark Dazikon',
  ダークねむり大根: 'Dark Dozikon',
  ダークみだれ大根: 'Dark Mesmerikon',
  # Naptapir
  うたたねバク: 'Naptapir',
  いねむりバク: 'Snooztapir',
  じゅくすいバク: 'Doztapir',
  とうみんバク: 'Comatapir',
  闇うたたねバク: 'Dark Naptapir',
  闇いねむりバク: 'Dark Snooztapir',
  闇じゅくすいバク: 'Dark Doztapir',
  闇とうみんバク: 'Dark Comatapir',
  # Swordsman
  ケンゴウ: 'Swordsman',
  イアイ: 'Fencer',
  シハン: 'Sensei',
  タツジン: 'Swordmaster',
  悪ケンゴウ: 'Evil Swordsman',
  悪イアイ: 'Evil Fencer',
  悪シハン: 'Evil Sensei',
  悪タツジン: 'Evil Swordmaster',
  # Mudkin
  ミドロ: 'Mudkin',
  ゲドロ: 'Muddy',
  オドロ: 'Mudster',
  チドロ: 'Mudder',
  ブラックミドロ: 'Shady Mudkin',
  ブラックゲドロ: 'Shady Muddy',
  ブラックオドロ: 'Shady Mudster',
  ブラックチドロ: 'Shady Mudder',
  # Polygon Spinna
  まわるポリゴン: 'Polygon Spinna',
  おどるポリゴン: 'Polygon Shaka',
  うたうポリゴン: 'Polygon Singa',
  らんぶポリゴン: 'Polygon Stunna',
  悪まわるポリゴン: 'Evil PolySpinna',
  悪おどるポリゴン: 'Evil PolyShaka',
  悪うたうポリゴン: 'Evil PolySinga',
  悪らんぶポリゴン: 'Evil PolyStunna',
  # Metalhead
  アイアンヘッド: 'Metalhead',
  チェインヘッド: 'Ironhead',
  ギガヘッド: 'Steelhead',
  デスヘッド: 'Doomhead',
  闇アイアンヘッド: 'Dark Metalhead',
  闇チェインヘッド: 'Dark Ironhead',
  闇ギガヘッド: 'Dark Steelhead',
  闇デスヘッド: 'Dark Doomhead',
  # Cheer-Ham
  フレフレハムポン: 'Cheer-Ham',
  ガンバレハムポン: 'Go-Ham!',
  ファイトハムポン: 'Rally Ham',
  アゲアゲハムポン: 'Spirit Ham',
  悪フレフレハムポン: 'Mean Cheer-Ham',
  悪ガンバレハムポン: 'Mean Go-Ham!',
  悪ファイトハムポン: 'Mean Rally Ham',
  悪アゲアゲハムポン: 'Mean Spirit Ham',
  # Kid Squid
  イカキング: 'Kid Squid',
  イカだいおう: 'Squidfficial',
  イカエンペラー: 'King Squid',
  イカカイザー: 'Squidperor',
  闇イカキング: 'Evil Kid Squid',
  闇イカだいおう: 'Evil Squidfficial',
  闇イカエンペラー: 'Evil King Squid',
  闇イカカイザー: 'Evil Squidperor',
  # Foly
  フォーリー: 'Foly',
  ダークフォーリー: 'Dark Foly',
  # Bored Kappa
  ひまガッパ: 'Bored Kappa',
  いやすぎガッパ: 'Kappa Pest',
  たまらんガッパ: 'Vexing Kappa',
  おてあげガッパ: 'Kappa Troll',
  闇ひまガッパ: 'Dark Bored Kappa',
  闇いやすぎガッパ: 'Dark Kappa Pest',
  闇たまらんガッパ: 'Dark Vexing Kappa',
  闇おてあげガッパ: 'Dark Kappa Troll',
  # Hopodile
  ピョコダイル: 'Hopodile',
  ピョンダイル: 'Hipadile',
  ボヨンダイル: 'Oingodile',
  バイーンダイル: 'Boingodile',
  悪ピョコダイル: 'Evil Hopodile',
  悪ピョンダイル: 'Evil Hipadile',
  悪ボヨンダイル: 'Evil Oingodile',
  悪バイーンダイル: 'Evil Boingodile',
  # Flamebird
  フラッシュバード: 'Flamebird',
  グレアバード: 'Sparkbird',
  ツインクルバード: 'Flarebird',
  シャインバード: 'Blazebird',
  闇フラッシュバード: 'Dark Flamebird',
  闇グレアバード: 'Dark Sparkbird',
  闇ツインクルバード: 'Dark Flarebird',
  闇シャインバード: 'Dark Blazebird',
  # Yanpii
  ヤンぴー: 'Yanpii',
  親衛ヤンぴー: 'Sr. Yanpii',
  副総長ヤンぴー: 'Lt. Yanpii',
  総長ヤンぴー: 'Boss Yanpii',
  闇ヤンぴー: 'Sinful Yanpii',
  闇親衛ヤンぴー: 'Sinful Sr. Yanpii',
  闇副総長ヤンぴー: 'Sinful Lt. Yanpii',
  闇総長ヤンぴー: 'Sinful Boss Yanpii',
  # Scoopie
  スコッピー: 'Scoopie',
  シャベッピー: 'Spadie',
  クワッピー: 'Trowelie',
  ユンピー: 'Shovelie',
  悪スコッピー: 'Wicked Scoopie',
  悪シャベッピー: 'Wicked Spadie',
  悪クワッピー: 'Wicked Trowelie',
  悪ユンピー: 'Wicked Shovelie',
  # Zalokleft
  ぬすっトド: 'Zalokleft',
  みどりトド: 'Green Zalokleft',
  アイアントド: 'Iron Zalokleft',
  しょうめつトド: 'Zalokleftis King',
  腹黒ぬすっトド: 'Bad Zalokleft',
  腹黒みどりトド: 'Bad G. Zalokleft',
  腹黒アイアントド: 'Bad I. Zalokleft',
  腹黒しょうめつトド: 'Bad Zalokleft King',
  # Eligan
  エリガン: 'Eligan',
  エリガガン: 'Eligagan',
  エリガゴン: 'Eligagon',
  エリズガゴン: 'Elizgagon',
  ダークエリガン: 'Dark Eligan',
  ダークエリガガン: 'Dark Eligagan',
  ダークエリガゴン: 'Dark Eligagon',
  ダークエリズガゴン: 'Dark Elizgagon',
  # Gyadon
  ギャドン: 'Gyadon',
  ギャイラス: 'Gyairas',
  ギャンドラー: 'Gyandora',
  ギャンドロン: 'Gyandoron',
  暴れギャドン: 'Violent Gyadon',
  暴れギャイラス: 'Violent Gyairas',
  暴れギャンドラー: 'Violent Gyandora',
  暴れギャンドロン: 'Violent Gyandoron',
  # Gazer
  ゲイズ: 'Gazer',
  スーパーゲイズ: 'Super Gazer',
  ハイパーゲイズ: 'Hyper Gazer',
  ゲンナマゲイズ: 'Ultra Gazer',
  悪ゲイズ: 'Evil Gazer',
  悪スーパーゲイズ: 'Evil Super Gazer',
  悪ハイパーゲイズ: 'Evil Hyper Gazer',
  悪ゲンナマゲイズ: 'Evil Ultra Gazer',
  # Zapdon
  バリズドン: 'Zapdon',
  ゴロズドン: 'Huistdon',
  ビカズドン: 'Bunchukdon',
  ドドズドン: 'Zotdon',
  ダークバリズドン: 'Dark Zapdon',
  ダークゴロズドン: 'Dark Huistdon',
  ダークビカズドン: 'Dark Bunchukdon',
  ダークドドズドン: 'Dark Zotdon',
  # Dragon
  ドラゴン: 'Dragon',
  スカイドラゴン: 'Sky Dragon',
  アークドラゴン: 'Archdragon',
  アビスドラゴン: 'Abyssal Dragon',
  悪ドラゴン: 'Evil Dragon',
  悪スカイドラゴン: 'Evil Sky Dragon',
  悪アークドラゴン: 'Evil Archdragon',
  悪アビスドラゴン: 'Evil Abyss Dragon',
  # DJ Mage
  ガラ魔道士: 'DJ Mage',
  ガラ中流魔道士: 'MC Mage',
  ガラ上流魔道士: 'MC Wizard',
  ガラ貴族魔道士: 'MC Sorceror',
  黒ガラ魔道士: 'Dark DJ Mage',
  黒ガラ中流魔道士: 'Dark MC Mage',
  黒ガラ上流魔道士: 'Dark MC Wizard',
  黒ガラ貴族魔道士: 'Dark MC Sorceror',
  # Porky
  デブータ: 'Porky',
  デブーチョ: 'Porko',
  デブートン: 'Porkon',
  デブーゴン: 'Porgon',
  悪デブータ: 'Sinister Porky',
  悪デブーチョ: 'Sinister Porko',
  悪デブートン: 'Sinister Porkon',
  悪デブーゴン: 'Sinister Porgon',
  # Boy Cart
  ボウヤカート: 'Boy Cart',
  クロスカート: 'Cross Cart',
  吹き飛びカート: 'Strong Cart',
  貫通カート: 'Pierce Cart',
  闇ボウヤカート: 'Dark Boy Cart',
  闇クロスカート: 'Dark Cross Cart',
  闇吹き飛びカート: 'Dark Strong Cart',
  闇貫通カート: 'Dark Pierce Cart',
  # Pop Tank
  オヤジ戦車: 'Pop Tank',
  ガンコ戦車: 'Grampa Tank',
  ゴウジョウ戦車: 'Ornery Tank',
  イッテツ戦車: 'Cranky Tank',
  闇オヤジ戦車: 'Dark Pop Tank',
  闇ガンコ戦車: 'Dark Grampa Tank',
  闇ゴウジョウ戦車: 'Dark Ornery Tank',
  闇イッテツ戦車: 'Dark Cranky Tank',
  # Absorbiphant
  すいだすゾウ: 'Absorbiphant',
  とりこむゾウ: 'Digestiphant',
  くみこむゾウ: 'Spongiderm',
  ひきこむゾウ: 'Osmammoth',
  闇すいだすゾウ: 'Dark Absorbiphant',
  闇とりこむゾウ: 'Dark Digestiphant',
  闇くみこむゾウ: 'Dark Spongiderm',
  闇ひきこむゾウ: 'Dark Osmammoth',
  # Punisher
  処刑者: 'Punisher',
  断罪者: 'Debaser',
  破壊者: 'Ruiner',
  崩壊者: 'Despoiler',
  地獄の処刑者: "Hell's Punisher",
  地獄の断罪者: "Hell's Debaser",
  地獄の破壊者: "Hell's Ruiner",
  地獄の崩壊者: "Hell's Despoiler",
  # Firepuff
  ヒーポフ: 'Firepuff',
  ホノオポフ: 'Flamepuff',
  カエンポフ: 'Blazepuff',
  ゴオオポフ: 'Pyrepuff',
  悪ヒーポフ: 'Evil Firepuff',
  悪ホノオポフ: 'Evil Flamepuff',
  悪カエンポフ: 'Evil Blazepuff',
  悪ゴオオポフ: 'Evil Pyrepuff',
  # Crow Tengu
  カラス天狗: 'Crow Tengu',
  ハヤブサ天狗: 'Falcon Tengu',
  イヌワシ天狗: 'Eagle Tengu',
  ホウオウ天狗: 'Phoenix Tengu',
  黒カラス天狗: 'Bad Crow Tengu',
  黒ハヤブサ天狗: 'Bad Falcon Tengu',
  黒イヌワシ天狗: 'Bad Eagle Tengu',
  黒ホウオウ天狗: 'Bad Phoenix Tengu',
  # FO-Uβ
  'ＦＯ－Ｕβ': 'FO-Uβ',
  'ＦＯ－Ｕ': 'FO-U',
  'ＦＯ－ＵＺ': 'FO-UZ',
  'ＦＯ－ＵＺＺ': 'FO-UZZ',
  'εＦＯ－Ｕβ': 'εFO-Uβ',
  'εＦＯ－Ｕ': 'εFI-U',
  'εＦＯ－ＵＺ': 'εFO-UZ',
  'εＦＯ－ＵＺＺ': 'εFO-UZZ',
  # Myriman
  ケダマン: 'Myriman',
  ケダーク: 'Billman',
  ケダッチョ: 'Trillman',
  ケダケー: 'Googoman',
  ダークケダマン: 'Dark Myriman',
  ダークケダーク: 'Dark Billman',
  ダークケダッチョ: 'Dark Trillman',
  ダークケダケー: 'Dark Googoman',
  # Moseal
  もざらし: 'Moseal',
  ももざらし: 'Momoseal',
  もももざらし: 'Momomoseal',
  ももももざらし: 'Momomomoseal',
  闇もざらし: 'Bad Moseal',
  闇ももざらし: 'Bad Momoseal',
  闇もももざらし: 'Bad Momomoseal',
  闇ももももざらし: 'Bad Momomomoseal',
  # Kumonigiri
  おにぎりクマ: 'Kumonigiri',
  おにぎりアナグマ: 'Pandanigiri',
  おにぎりツキノワ: 'Onigirizzly',
  おにぎりヒグマ: 'Kodionigiri',
  闇おにぎりクマ: 'Dark Kumonigiri',
  闇おにぎりアナグマ: 'Dark Pandanigiri',
  闇おにぎりツキノワ: 'Dark Onigirizzly',
  闇おにぎりヒグマ: 'Dark Kodionigiri',
  # Shagga
  シャーガ: 'Shagga',
  ナシャーガ: 'Nashagga',
  ラシャーガ: 'Lashagga',
  バシャーガ: 'Bashagga',
  エビルシャーガ: 'Filthy Shagga',
  エビルナシャーガ: 'Filthy Nashagga',
  エビルラシャーガ: 'Filthy Lashagga',
  エビルバシャーガ: 'Filthy Bashagga',
  # Explochin
  ばくだんウニ: 'Explochin',
  ばくれつウニ: 'Concusschin',
  ふんかウニ: 'Fulminachin',
  だいふんかウニ: 'Detonachin',
  悪ばくだんウニ: 'Evil Explochin',
  悪ばくれつウニ: 'Evil Concusschin',
  悪ふんかウニ: 'Evil Fulminachin',
  悪だいふんかウニ: 'Evil Detonachin',
  # Chow
  タベラレルー: 'Chow',
  クダカレルー: 'Snacky',
  トカサレルー: 'Munchy',
  トリコマレルー: 'Mealy',
  欲タベラレルー: 'Plump Chow',
  欲クダカレルー: 'Plump Snacky',
  欲トカサレルー: 'Plump Munchy',
  欲トリコマレルー: 'Plump Mealy',
  # Field Knave
  畠荒らし: 'Field Knave',
  壺荒らし: 'Pot Knave',
  物荒らし: 'Item Knave',
  大物荒らし: 'Knave King',
  闇畠荒らし: 'Dark Field Knave',
  闇壺荒らし: 'Dark Pot Knave',
  闇物荒らし: 'Dark Item Knave',
  闇大物荒らし: 'Dark Knave King',
  # Maneater
  ひとくいデビル: 'Maneater',
  むらぐいデビル: 'Villeater',
  やまぐいデビル: 'Mounteater',
  しまぐいデビル: 'Isleater',
  闇ひとくいデビル: 'Dark Maneater',
  闇むらぐいデビル: 'Dark Villeater',
  闇やまぐいデビル: 'Dark Mounteater',
  闇しまぐいデビル: 'Dark Isleater'
}.with_indifferent_access

effective = {
  Sproutant: '<span class="green_text">Anti-Plant</span>',
  Sproutyrant: '<span class="green_text">Anti-Plant</span>',
  Sprouterror: '<span class="green_text">Anti-Plant</span>',
  Sproutitan: '<span class="green_text">Anti-Plant</span>',
  Seedie: '<span class="green_text">Anti-Plant</span>',
  Beanie: '<span class="green_text">Anti-Plant</span>',
  Nuttie: '<span class="green_text">Anti-Plant</span>',
  Grainie: '<span class="green_text">Anti-Plant</span>',
  'Grass Boy': '<span class="green_text">Anti-Plant</span>',
  'Grass Bro': '<span class="green_text">Anti-Plant</span>',
  'Grass Guy': '<span class="green_text">Anti-Plant</span>',
  'Grass Gramps': '<span class="green_text">Anti-Plant</span>',
  'Pin Kid': '<span class="green_text">Anti-Plant</span>',
  'Pin Dude': '<span class="green_text">Anti-Plant</span>',
  'Pin Poppa': '<span class="green_text">Anti-Plant</span>',
  'Pin Gramps': '<span class="green_text">Anti-Plant</span>',
  'Sweet Nut': '<span class="green_text">Anti-Plant</span><br><span class="green_text">Anti-Explode</span>',
  'Acrid Nut': '<span class="green_text">Anti-Plant</span><br><span class="green_text">Anti-Explode</span>',
  'Spicy Nut': '<span class="green_text">Anti-Plant</span><br><span class="green_text">Anti-Explode</span>',
  'Bitter Nut': '<span class="green_text">Anti-Plant</span><br><span class="green_text">Anti-Explode</span>',
  'Blade Bee': '<span class="green_text">Anti-Floating</span><br><span class="blue_text_3">Anti-Cnf. Bracelet</span>',
  'Dagger Bee': '<span class="green_text">Anti-Floating</span><br><span class="blue_text_3">Anti-Cnf. Bracelet</span>',
  'Katana Bee': '<span class="green_text">Anti-Floating</span><br><span class="blue_text_3">Anti-Cnf. Bracelet</span>',
  Zanbeeto: '<span class="green_text">Anti-Floating</span><br><span class="blue_text_3">Anti-Cnf. Bracelet</span>',
  'Dark Blade Bee': '<span class="blue_text_3">Anti-Cnf. Bracelet</span>',
  'Dark Dagger Bee': '<span class="blue_text_3">Anti-Cnf. Bracelet</span>',
  'Dark Katana Bee': '<span class="blue_text_3">Anti-Cnf. Bracelet</span>',
  'Dark Zanbeeto': '<span class="blue_text_3">Anti-Cnf. Bracelet</span>',
  'Nigiri Morph': '<span class="green_text">Anti-Onigiri</span><br>Bless items',
  'Nigiri Boss': '<span class="green_text">Anti-Onigiri</span><br>Bless items',
  'Nigiri King': '<span class="green_text">Anti-Onigiri</span><br>Bless items',
  'Foul Nigiri Morph': '<span class="green_text">Anti-Onigiri</span><br>Bless items',
  'Foul Nigiri Boss': '<span class="green_text">Anti-Onigiri</span><br>Bless items',
  'Foul Nigiri King': '<span class="green_text">Anti-Onigiri</span><br>Bless items',
  Froggo: '<span class="green_text">Anti-Burgle</span>',
  Froggucci: '<span class="green_text">Anti-Burgle</span>',
  Froggon: '<span class="green_text">Anti-Burgle</span>',
  Kleptoad: '<span class="green_text">Anti-Burgle</span>',
  'Snide Froggo': '<span class="green_text">Anti-Burgle</span>',
  'Snide Froggucci': '<span class="green_text">Anti-Burgle</span>',
  'Snide Froggon': '<span class="green_text">Anti-Burgle</span>',
  'Snide Kleptoad': '<span class="green_text">Anti-Burgle</span>',
  Karakuroid: '<span class="green_text">Anti-Metal</span>',
  Steamroid: '<span class="green_text">Anti-Metal</span>',
  Electroid: '<span class="green_text">Anti-Metal</span>',
  Cyberoid: '<span class="green_text">Anti-Metal</span>',
  'Tiger Tosser': '<span class="green_text">Unmoving</span>',
  'Tiger Hurler': '<span class="green_text">Unmoving</span>',
  'Tiger Chucker': '<span class="green_text">Unmoving</span>',
  'Tiger Ace': '<span class="green_text">Unmoving</span>',
  'Dark Tosser': '<span class="green_text">Unmoving</span>',
  'Dark Hurler': '<span class="green_text">Unmoving</span>',
  'Dark Chucker': '<span class="green_text">Unmoving</span>',
  'Dark Ace': '<span class="green_text">Unmoving</span>',
  'Curse Girl': '<span class="blue_text_3">Anti-Crs. Bracelet</span>',
  Cursister: '<span class="blue_text_3">Anti-Crs. Bracelet</span>',
  Curspinster: '<span class="blue_text_3">Anti-Crs. Bracelet</span>',
  Cursenior: '<span class="blue_text_3">Anti-Crs. Bracelet</span>',
  'Foul Curse Girl': '<span class="blue_text_3">Anti-Crs. Bracelet</span>',
  'Foul Cursister': '<span class="blue_text_3">Anti-Crs. Bracelet</span>',
  'Foul Curspinster': '<span class="blue_text_3">Anti-Crs. Bracelet</span>',
  'Foul Cursenior': '<span class="blue_text_3">Anti-Crs. Bracelet</span>',
  Fearabbit: '<span class="green_text">Anti-Magic</span><br><span class="green_text">Unmoving</span>',
  Scarabbit: '<span class="green_text">Anti-Magic</span><br><span class="green_text">Unmoving</span>',
  Horrabbit: '<span class="green_text">Anti-Magic</span><br><span class="green_text">Unmoving</span>',
  Terrabbit: '<span class="green_text">Anti-Magic</span><br><span class="green_text">Unmoving</span>',
  'Dark Fearabbit': '<span class="green_text">Unmoving</span>',
  'Dark Scarabbit': '<span class="green_text">Unmoving</span>',
  'Dark Horrabbit': '<span class="green_text">Unmoving</span>',
  'Dark Terrabbit': '<span class="green_text">Unmoving</span>',
  Gyaza: '<span class="green_text">Anti-Aquatic</span>',
  'Death Gyaza': '<span class="green_text">Anti-Aquatic</span>',
  'Hell Gyaza': '<span class="green_text">Anti-Aquatic</span>',
  'Doom Gyaza': '<span class="green_text">Anti-Aquatic</span>',
  Pumphantasm: '<span class="green_text">Anti-Plant</span><br><span class="green_text">Anti-Floating</span>',
  Pumphantom: '<span class="green_text">Anti-Plant</span><br><span class="green_text">Anti-Floating</span>',
  Pumpanshee: '<span class="green_text">Anti-Plant</span><br><span class="green_text">Anti-Floating</span>',
  Pumptergeist: '<span class="green_text">Anti-Plant</span><br><span class="green_text">Anti-Floating</span>',
  "N'dubba": '<span class="green_text">Anti-Metal</span>',
  "N'twyn": '<span class="green_text">Anti-Metal</span>',
  "N'mach": '<span class="green_text">Anti-Metal</span>',
  "N'dup": '<span class="green_text">Anti-Metal</span>',
  Scorpion: '<span class="green_text">Anti-Drain</span><br><span class="blue_text_3">Cleansing Bracelet</span>',
  VeniScorp: '<span class="green_text">Anti-Drain</span><br><span class="blue_text_3">Cleansing Bracelet</span>',
  StunScorp: '<span class="green_text">Anti-Drain</span><br><span class="blue_text_3">Cleansing Bracelet</span>',
  BlightScorp: '<span class="green_text">Anti-Drain</span><br><span class="blue_text_3">Cleansing Bracelet</span>',
  'Dark Scorpion': '<span class="blue_text_3">Cleansing Bracelet</span>',
  'Dark VeniScorp': '<span class="blue_text_3">Cleansing Bracelet</span>',
  'Dark StunScorp': '<span class="blue_text_3">Cleansing Bracelet</span>',
  'Dark BlightScorp': '<span class="blue_text_3">Cleansing Bracelet</span>',
  Mutaikon: '<span class="green_text">Anti-Plant</span><br><span class="blue_text_3">Cleansing Bracelet</span>',
  Dazikon: '<span class="green_text">Anti-Plant</span><br><span class="blue_text_3">Anti-Cnf. Bracelet</span>',
  Dozikon: '<span class="green_text">Anti-Plant</span><br><span class="blue_text_3">Alert Bracelet</span>',
  Mesmerikon: '<span class="green_text">Anti-Plant</span><br><span class="blue_text_3">Dodger Pot</span>',
  'Dark Mutaikon': '<span class="blue_text_3">Cleansing Bracelet</span>',
  'Dark Dazikon': '<span class="blue_text_3">Anti-Cnf. Bracelet</span>',
  'Dark Dozikon': '<span class="blue_text_3">Alert Bracelet</span>',
  'Dark Mesmerikon': '<span class="blue_text_3">Dodger Pot</span>',
  Naptapir: '<span class="blue_text_3">Alert Bracelet</span>',
  Snooztapir: '<span class="blue_text_3">Alert Bracelet</span>',
  Doztapir: '<span class="blue_text_3">Alert Bracelet</span>',
  Comatapir: '<span class="blue_text_3">Alert Bracelet</span>',
  'Dark Naptapir': '<span class="blue_text_3">Alert Bracelet</span>',
  'Dark Snooztapir': '<span class="blue_text_3">Alert Bracelet</span>',
  'Dark Doztapir': '<span class="blue_text_3">Alert Bracelet</span>',
  'Dark Comatapir': '<span class="blue_text_3">Alert Bracelet</span>',
  Swordsman: '<span class="blue_text_3">Anti-Parry Brce.</span>',
  Fencer: '<span class="blue_text_3">Anti-Parry Brce.</span>',
  Sensei: '<span class="blue_text_3">Anti-Parry Brce.</span>',
  Swordmaster: '<span class="blue_text_3">Anti-Parry Brce.</span>',
  'Evil Swordsman': '<span class="blue_text_3">Anti-Parry Brce.</span>',
  'Evil Fencer': '<span class="blue_text_3">Anti-Parry Brce.</span>',
  'Evil Sensei': '<span class="blue_text_3">Anti-Parry Brce.</span>',
  'Evil Swordmaster': '<span class="blue_text_3">Anti-Parry Brce.</span>',
  Mudkin: '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Rustproof</span>',
  Muddy: '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Rustproof</span>',
  Mudster: '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Rustproof</span>',
  Mudder: '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Rustproof</span><br><span class="blue_text_3">Monster Detector</span>',
  'Shady Mudkin': '<span class="green_text">Rustproof</span>',
  'Shady Muddy': '<span class="green_text">Rustproof</span>',
  'Shady Mudster': '<span class="green_text">Rustproof</span>',
  'Shady Mudder': '<span class="green_text">Rustproof</span><br><span class="blue_text_3">Monster Detector</span>',
  'Polygon Spinna': '<span class="green_text">Anti-Drain</span><br><span class="green_text">Anti-Magic</span><br><span class="blue_text_3">Staunch Bracelet</span>',
  'Polygon Shaka': '<span class="green_text">Anti-Drain</span><br><span class="green_text">Anti-Magic</span><br><span class="blue_text_3">Staunch Bracelet</span>',
  'Polygon Singa': '<span class="green_text">Anti-Drain</span><br><span class="green_text">Anti-Magic</span><br><span class="blue_text_3">Staunch Bracelet</span>',
  'Polygon Stunna': '<span class="green_text">Anti-Drain</span><br><span class="green_text">Anti-Magic</span><br><span class="blue_text_3">Staunch Bracelet</span>',
  'Evil PolySpinna': '<span class="blue_text_3">Staunch Bracelet</span>',
  'Evil PolyShaka': '<span class="blue_text_3">Staunch Bracelet</span>',
  'Evil PolySinga': '<span class="blue_text_3">Staunch Bracelet</span>',
  'Evil PolyStunna': '<span class="blue_text_3">Staunch Bracelet</span>',
  'Metalhead': '<span class="green_text">Anti-Cyclops</span>',
  'Ironhead': '<span class="green_text">Anti-Cyclops</span>',
  'Steelhead': '<span class="green_text">Anti-Cyclops</span>',
  'Doomhead': '<span class="green_text">Anti-Cyclops</span>',
  'Kid Squid': '<span class="green_text">Anti-Aquatic</span>',
  'Squidfficial': '<span class="green_text">Anti-Aquatic</span>',
  'Kind Squid': '<span class="green_text">Anti-Aquatic</span>',
  'Squidperor': '<span class="green_text">Anti-Aquatic</span>',
  'Foly': '<span class="green_text">Anti-Cyclops</span><br><span class="green_text">Anti-Floating</span>',
  'Bored Kappa': '<span class="green_text">Anti-Aquatic</span>',
  'Kappa Pest': '<span class="green_text">Anti-Aquatic</span><br><span class="blue_text_3">Dodger Pot</span>',
  'Vexing Kappa': '<span class="green_text">Anti-Aquatic</span><br><span class="blue_text_3">Dodger Pot</span>',
  'Kappa Troll': '<span class="green_text">Anti-Aquatic</span><br><span class="blue_text_3">Dodger Pot</span>',
  'Dark Kappa Pest': '<span class="blue_text_3">Dodger Pot</span>',
  'Dark Vexing Kappa': '<span class="blue_text_3">Dodger Pot</span>',
  'Dark Kappa Troll': '<span class="blue_text_3">Dodger Pot</span>',
  'Hopodile': '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Anti-Dragon</span>',
  'Hipadile': '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Anti-Dragon</span>',
  'Oingodile': '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Anti-Dragon</span>',
  'Boingodile': '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Anti-Dragon</span>',
  'Flamebird': '<span class="green_text">Anti-Floating</span>',
  'Sparkbird': '<span class="green_text">Anti-Floating</span>',
  'Flarebird': '<span class="green_text">Anti-Floating</span>',
  'Blazebird': '<span class="green_text">Anti-Floating</span>',
  'Yanpii': '<span class="green_text">Unmoving</span>',
  'Sr. Yanpii': '<span class="green_text">Unmoving</span>',
  'Lt. Yanpii': '<span class="green_text">Unmoving</span>',
  'Boss Yanpii': '<span class="green_text">Unmoving</span>',
  'Sinful Yanpii': '<span class="green_text">Unmoving</span>',
  'Sinful Sr. Yanpii': '<span class="green_text">Unmoving</span>',
  'Sinful Lt. Yanpii': '<span class="green_text">Unmoving</span>',
  'Sinful Boss Yanpii': '<span class="green_text">Unmoving</span>',
  'Scoopie': '<span class="green_text">Anti-Metal</span><br><span class="blue_text_3">Dodger Pot</span>',
  'Spadie': '<span class="green_text">Anti-Metal</span><br><span class="blue_text_3">Dodger Pot</span>',
  'Trowelie': '<span class="green_text">Anti-Metal</span><br><span class="blue_text_3">Dodger Pot</span>',
  'Shovelie': '<span class="green_text">Anti-Metal</span><br><span class="blue_text_3">Dodger Pot</span>',
  'Wicked Scoopie': '<span class="blue_text_3">Dodger Pot</span>',
  'Wicked Spadie': '<span class="blue_text_3">Dodger Pot</span>',
  'Wicked Trowelie': '<span class="blue_text_3">Dodger Pot</span>',
  'Wicked Shovelie': '<span class="blue_text_3">Dodger Pot</span>',
  'Zalokleft': '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Anti-Theft</span>',
  'Green Zalokleft': '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Anti-Theft</span>',
  'Iron Zalokleft': '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Anti-Theft</span>',
  'Zalokleftis King': '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Anti-Theft</span>',
  'Bad Zalokleft': '<span class="green_text">Anti-Theft</span>',
  'Bad G. Zalokleft': '<span class="green_text">Anti-Theft</span>',
  'Bad I. Zalokleft': '<span class="green_text">Anti-Theft</span>',
  'Bad Zalokleft King': '<span class="green_text">Anti-Theft</span>',
  'Gyadon': '<span class="green_text">Anti-Floating</span><br><span class="green_text">Anti-Peck</span>',
  'Gyairas': '<span class="green_text">Anti-Floating</span><br><span class="green_text">Anti-Peck</span>',
  'Gyandora': '<span class="green_text">Anti-Floating</span><br><span class="green_text">Anti-Peck</span>',
  'Gyandoron': '<span class="green_text">Anti-Floating</span><br><span class="green_text">Anti-Peck</span>',
  'Violent Gyadon': '<span class="green_text">Anti-Peck</span>',
  'Violent Gyairas': '<span class="green_text">Anti-Peck</span>',
  'Violent Gyandora': '<span class="green_text">Anti-Peck</span>',
  'Violent Gyandoron': '<span class="green_text">Anti-Peck</span>',
  'Gazer': '<span class="green_text">Anti-Cyclops</span><br><span class="green_text">Anti-Magic</span><br><span class="green_text">Anti-Hypno</span>',
  'Super Gazer': '<span class="green_text">Anti-Cyclops</span><br><span class="green_text">Anti-Magic</span><br><span class="green_text">Anti-Hypno</span>',
  'Hyper Gazer': '<span class="green_text">Anti-Cyclops</span><br><span class="green_text">Anti-Magic</span><br><span class="green_text">Anti-Hypno</span>',
  'Ultra Gazer': '<span class="green_text">Anti-Cyclops</span><br><span class="green_text">Anti-Magic</span><br><span class="green_text">Anti-Hypno</span>',
  'Evil Gazer': '<span class="green_text">Anti-Hypno</span>',
  'Evil Super Gazer': '<span class="green_text">Anti-Hypno</span>',
  'Evil Hyper Gazer': '<span class="green_text">Anti-Hypno</span>',
  'Evil Ultra Gazer': '<span class="green_text">Anti-Hypno</span>',
  'Dragon': '<span class="green_text">Anti-Dragon</span><br><span class="green_text">Anti-Fire</span>',
  'Sky Dragon': '<span class="green_text">Anti-Dragon</span><br><span class="green_text">Anti-Fire</span><br><span class="blue_text_3">Zen Pot</span>',
  'Archdragon': '<span class="green_text">Anti-Dragon</span><br><span class="green_text">Anti-Fire</span><br><span class="blue_text_3">Zen Pot</span>',
  'Abyssal Dragon': '<span class="green_text">Anti-Dragon</span><br><span class="green_text">Anti-Fire</span><br><span class="blue_text_3">Zen Pot</span>',
  'Evil Dragon': '<span class="green_text">Anti-Fire</span>',
  'Evil Sky Dragon': '<span class="green_text">Anti-Fire</span><br><span class="blue_text_3">Zen Pot</span>',
  'Evil Archdragon': '<span class="green_text">Anti-Fire</span><br><span class="blue_text_3">Zen Pot</span>',
  'Evil Abyss Dragon': '<span class="green_text">Anti-Fire</span><br><span class="blue_text_3">Zen Pot</span>',
  'DJ Mage': '<span class="green_text">Anti-Magic</span><br><span class="green_text">Magi-Twister</span>',
  'MC Mage': '<span class="green_text">Anti-Magic</span><br><span class="green_text">Magi-Twister</span>',
  'MC Wizard': '<span class="green_text">Anti-Magic</span><br><span class="green_text">Magi-Twister</span><br><span class="blue_text_3">Reflection Pot</span>',
  'MC Sorceror': '<span class="green_text">Anti-Magic</span><br><span class="green_text">Magi-Twister</span><br><span class="blue_text_3">Reflection Pot</span>',
  'Dark DJ Mage': '<span class="green_text">Magi-Twister</span>',
  'Dark MC Mage': '<span class="green_text">Magi-Twister</span>',
  'Dark MC Wizard': '<span class="green_text">Magi-Twister</span><br><span class="blue_text_3">Reflection Pot</span>',
  'Dark MC Sorceror': '<span class="green_text">Magi-Twister</span><br><span class="blue_text_3">Reflection Pot</span>',
  'Porko': '<span class="blue_text_3">Dodger Pot</span>',
  'Porkon': '<span class="blue_text_3">Dodger Pot</span>',
  'Porgon': '<span class="blue_text_3">Dodger Pot</span>',
  'Sinister Porko': '<span class="blue_text_3">Dodger Pot</span>',
  'Sinister Porkon': '<span class="blue_text_3">Dodger Pot</span>',
  'Sinister Porgon': '<span class="blue_text_3">Dodger Pot</span>',
  'Boy Cart': '<span class="blue_text_3">Dodger Pot</span>',
  'Cross Cart': '<span class="blue_text_3">Dodger Pot</span>',
  'Strong Cart': '<span class="blue_text_3">Dodger Pot</span>',
  'Pierce Cart': '<span class="blue_text_3">Dodger Pot</span>',
  'Dark Boy Cart': '<span class="blue_text_3">Dodger Pot</span>',
  'Dark Cross Cart': '<span class="blue_text_3">Dodger Pot</span>',
  'Dark Strong Cart': '<span class="blue_text_3">Dodger Pot</span>',
  'Dark Pierce Cart': '<span class="blue_text_3">Dodger Pot</span>',
  'Pop Tank': '<span class="green_text">Anti-Metal</span><br><span class="green_text">Anti-Explode</span><br><span class="green_text">Anti-Blast</span><br><span class="blue_text_3">Zen Pot</span>',
  'Grampa Tank': '<span class="green_text">Anti-Metal</span><br><span class="green_text">Anti-Explode</span><br><span class="green_text">Anti-Blast</span><br><span class="blue_text_3">Zen Pot</span>',
  'Ornery Tank': '<span class="green_text">Anti-Metal</span><br><span class="green_text">Anti-Explode</span><br><span class="green_text">Anti-Blast</span><br><span class="blue_text_3">Zen Pot</span>',
  'Cranky Tank': '<span class="green_text">Anti-Metal</span><br><span class="green_text">Anti-Explode</span><br><span class="green_text">Anti-Blast</span><br><span class="blue_text_3">Zen Pot</span>',
  'Dark Pop Tank': '<span class="green_text">Anti-Blast</span><br><span class="blue_text_3">Zen Pot</span>',
  'Dark Grampa Tank': '<span class="green_text">Anti-Blast</span><br><span class="blue_text_3">Zen Pot</span>',
  'Dark Ornery Tank': '<span class="green_text">Anti-Blast</span><br><span class="blue_text_3">Zen Pot</span>',
  'Dark Cranky Tank': '<span class="green_text">Anti-Blast</span><br><span class="blue_text_3">Zen Pot</span>',
  'Absorbiphant': '<span class="green_text">Anti-Drain</span>',
  'Digestiphant': '<span class="green_text">Anti-Drain</span>',
  'Spongiderm': '<span class="green_text">Anti-Drain</span>',
  'Osmammoth': '<span class="green_text">Anti-Drain</span>',
  'Punisher': '<span class="blue_text_3">Water Pot</span>',
  'Debaser': '<span class="blue_text_3">Water Pot</span>',
  'Ruiner': '<span class="blue_text_3">Water Pot</span>',
  'Despoiler': '<span class="blue_text_3">Water Pot</span>',
  "Hell's Punisher": '<span class="blue_text_3">Water Pot</span>',
  "Hell's Debaser": '<span class="blue_text_3">Water Pot</span>',
  "Hell's Ruiner": '<span class="blue_text_3">Water Pot</span>',
  "Hell's Despoiler": '<span class="blue_text_3">Water Pot</span>',
  'Firepuff': '<span class="green_text">Anti-Dragon</span><br><span class="green_text">Anti-Floating</span><br><span class="green_text">Anti-Fire</span>',
  'Flamepuff': '<span class="green_text">Anti-Dragon</span><br><span class="green_text">Anti-Floating</span><br><span class="green_text">Anti-Fire</span>',
  'Blazepuff': '<span class="green_text">Anti-Dragon</span><br><span class="green_text">Anti-Floating</span><br><span class="green_text">Anti-Fire</span>',
  'Pyrepuff': '<span class="green_text">Anti-Dragon</span><br><span class="green_text">Anti-Floating</span><br><span class="green_text">Anti-Fire</span>',
  'Evil Firepuff': '<span class="green_text">Anti-Fire</span>',
  'Evil Flamepuff': '<span class="green_text">Anti-Fire</span>',
  'Evil Blazepuff': '<span class="green_text">Anti-Fire</span>',
  'Evil Pyrepuff': '<span class="green_text">Anti-Fire</span>',
  'Crow Tengu': '<span class="green_text">Anti-Floating</span>',
  'Falcon Tengu': '<span class="green_text">Anti-Floating</span>',
  'Eagle Tengu': '<span class="green_text">Anti-Floating</span>',
  'Phoenix Tengu': '<span class="green_text">Anti-Floating</span>',
  'FO-Uβ': '<span class="green_text">Anti-Metal</span><br><span class="green_text">Anti-Floating</span>',
  'FO-U': '<span class="green_text">Anti-Metal</span><br><span class="green_text">Anti-Floating</span>',
  'FO-UZ': '<span class="green_text">Anti-Metal</span><br><span class="green_text">Anti-Floating</span>',
  'FO-UZZ': '<span class="green_text">Anti-Metal</span><br><span class="green_text">Anti-Floating</span>',
  'Myriman': '<span class="green_text">Anti-Drain</span>',
  'Billman': '<span class="green_text">Anti-Drain</span>',
  'Trillman': '<span class="green_text">Anti-Drain</span>',
  'Googoman': '<span class="green_text">Anti-Drain</span>',
  'Moseal': '<span class="green_text">Anti-Aquatic</span>',
  'Momoseal': '<span class="green_text">Anti-Aquatic</span>',
  'Momomoseal': '<span class="green_text">Anti-Aquatic</span>',
  'Momomomoseal': '<span class="green_text">Anti-Aquatic</span>',
  'Shagga': '<span class="green_text">Anti-Dragon</span><br><span class="blue_text_3">Water Pot</span>',
  'Nashagga': '<span class="green_text">Anti-Dragon</span><br><span class="blue_text_3">Water Pot</span>',
  'Lashagga': '<span class="green_text">Anti-Dragon</span><br><span class="blue_text_3">Water Pot</span>',
  'Bashagga': '<span class="green_text">Anti-Dragon</span><br><span class="blue_text_3">Water Pot</span>',
  'Filthy Shagga': '<span class="blue_text_3">Water Pot</span>',
  'Filthy Nashagga': '<span class="blue_text_3">Water Pot</span>',
  'Filthy Lashagga': '<span class="blue_text_3">Water Pot</span>',
  'Filthy Bashagga': '<span class="blue_text_3">Water Pot</span>',
  'Explochin': '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Anti-Cyclops</span><br><span class="green_text">Anti-Explode</span><br><span class="green_text">Anti-Blast</span>',
  'Concusschin': '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Anti-Cyclops</span><br><span class="green_text">Anti-Explode</span><br><span class="green_text">Anti-Blast</span>',
  'Fulminachin': '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Anti-Cyclops</span><br><span class="green_text">Anti-Explode</span><br><span class="green_text">Anti-Blast</span>',
  'Detonachin': '<span class="green_text">Anti-Aquatic</span><br><span class="green_text">Anti-Cyclops</span><br><span class="green_text">Anti-Explode</span><br><span class="green_text">Anti-Blast</span>',
  'Evil Explochin': '<span class="green_text">Anti-Blast</span>',
  'Evil Concusschin': '<span class="green_text">Anti-Blast</span>',
  'Evil Fulminachin': '<span class="green_text">Anti-Blast</span>',
  'Evil Detonachin': '<span class="green_text">Anti-Blast</span>',
  'Pot Knave': '<span class="blue_text_3">Anti-Parry Brce.</span>',
  'Item Knave': '<span class="blue_text_3">Anti-Parry Brce.</span>',
  'Knave King': '<span class="blue_text_3">Anti-Parry Brce.</span>',
  'Chow': '<span class="green_text">Anti-Floating</span>',
  'Snacky': '<span class="green_text">Anti-Floating</span>',
  'Munchy': '<span class="green_text">Anti-Floating</span>',
  'Mealy': '<span class="green_text">Anti-Floating</span>'
}.with_indifferent_access

notes = {
  'Cave Mamel': 'Direct attacks deal 1 damage.',
  'Gitan Mamel': 'Swift 2, direct attacks deal 1 damage, drops 2000G.',
  'Dark Gitan Mamel': 'Swift 2, drops 2000G.',
  'Sproutant': 'Resists status condition after one is inflicted.',
  'Sproutyrant': 'Resists status condition after one is inflicted.',
  'Sprouterror': 'Resists status condition after one is inflicted.',
  'Sproutitan': 'Resists status condition after one is inflicted.',
  'Vile Sproutant': 'Resists status condition after one is inflicted.',
  'Vile Sproutyrant': 'Resists status condition after one is inflicted.',
  'Vile Sprouterror': 'Resists status condition after one is inflicted.',
  'Vile Sproutitan': 'Resists status condition after one is inflicted.',
  'Colum': 'Rolls backward 10 tiles when defeated.',
  'Cololum': 'Rolls backward 10 tiles when defeated.',
  'Colocolum': 'Rolls backward 10 tiles when defeated.',
  'Colocolocolum': 'Rolls backward 10 tiles when defeated.',
  'Bad Colum': 'Rolls backward 10 tiles when defeated.',
  'Bad Cololum': 'Rolls backward 10 tiles when defeated.',
  'Bad Colocolum': 'Rolls backward 10 tiles when defeated.',
  'Bad Colocolocolum': 'Rolls backward 10 tiles when defeated.',
  'Seedie': 'Deals 6-8 damage without a shield.',
  'Grass Boy': 'Throws grass, drops 1 grass item.',
  'Grass Bro': 'Throws grass, drops up to 2 grass items.',
  'Grass Guy': 'Throws grass, drops up to 3 grass items.',
  'Grass Gramps': 'Throws grass, drops up to 4 grass items.',
  'Dark Grass Boy': 'Throws grass, drops 1 grass item.',
  'Dark Grass Bro': 'Throws grass, drops up to 2 grass items.',
  'Dark Grass Guy': 'Throws grass, drops up to 3 grass items.',
  'Dark Grass Gramps': 'Throws grass, drops up to 4 grass items.',
  'Pin Kid': 'Swift 1, becomes Grass Boy if it finds grass.',
  'Pin Dude': 'Swift 1, becomes Grass Bro if it finds grass.',
  'Pin Poppa': 'Swift 1, becomes Grass Guy if it finds grass.',
  'Pin Gramps': 'Swift 1, becomes Grass Gramps if it finds grass.',
  'Foul Pin Kid': 'Swift 1, becomes Dark Grass Boy if it finds grass.',
  'Foul Pin Dude': 'Swift 1, becomes Dark Grass Boy if it finds grass.',
  'Foul Pin Poppa': 'Swift 1, becomes Dark Grass Boy if it finds grass.',
  'Foul Pin Gramps': 'Swift 1, becomes Dark Grass Boy if it finds grass.',
  'Sweet Nut': 'Eats thrown items to multiply exp, but might explode.',
  'Acrid Nut': 'Eats thrown items to multiply exp, but might explode.',
  'Spicy Nut': 'Eats thrown items to multiply exp, but might explode.',
  'Bitter Nut': 'Eats thrown items to multiply exp, but might explode.',
  'Putrid Sweet Nut': 'Eats thrown items to multiply exp, but might explode.',
  'Putrid Acrid Nut': 'Eats thrown items to multiply exp, but might explode.',
  'Putrid Spicy Nut': 'Eats thrown items to multiply exp, but might explode.',
  'Putrid Bitter Nut': 'Eats thrown items to multiply exp, but might explode.',
  'Blade Bee': 'Stinger inflicts Confused, and then it collapses.',
  'Dagger Bee': 'Stinger inflicts Confused, and then it collapses.',
  'Katana Bee': 'Stinger inflicts Confused, and then it collapses.',
  'Zanbeeto': 'Stinger inflicts Confused, and then it collapses.',
  'Dark Blade Bee': 'Stinger inflicts Confused, and then it collapses.',
  'Dark Dagger Bee': 'Stinger inflicts Confused, and then it collapses.',
  'Dark Katana Bee': 'Stinger inflicts Confused, and then it collapses.',
  'Dark Zanbeeto': 'Stinger inflicts Confused, and then it collapses.',
  'Nigiri Morph': 'Turns an item into a Large Onigiri.',
  'Nigiri Boss': 'Inflicts Shiren with Onigiri status.',
  'Nigiri King': 'Turns an item or Shiren into an onigiri.',
  'Foul Nigiri Morph': 'Turns an item into a Large Onigiri.',
  'Foul Nigiri Boss': 'Inflicts Shiren with Onigiri status.',
  'Foul Nigiri King': 'Turns an item or Shiren into an onigiri.',
  'Froggo': 'Steals Gitan and warps away.',
  'Froggucci': 'Steals Gitan and warps away.',
  'Froggon': 'Steals Gitan and warps away.',
  'Kleptoad': 'Steals Gitan, throws Gitan from up to 10 tiles away.',
  'Snide Froggo': 'Steals Gitan and warps away.',
  'Snide Froggucci': 'Steals Gitan and warps away.',
  'Snide Froggon': 'Steals Gitan and warps away.',
  'Snide Kleptoad': 'Steals Gitan, throws Gitan from up to 10 tiles away.',
  'Karakuroid': 'Swift 1, creates traps.',
  'Steamroid': 'Swift 1, creates traps.',
  'Electroid': 'Swift 1, creates traps.',
  'Cyberoid': 'Swift 1, creates traps.',
  'Dark Karakuroid': 'Swift 1, creates traps.',
  'Dark Steamroid': 'Swift 1, creates traps.',
  'Dark Electroid': 'Swift 1, creates traps.',
  'Dark Cyberoid': 'Swift 1, creates traps.',
  'Tiger Tosser': 'Throws creatures up to 5 tiles away.',
  'Tiger Hurler': 'Throws creatures up to 10 tiles away.',
  'Tiger Chucker': 'Throws creatures up to 15 tiles away.',
  'Tiger Ace': 'Throws creatures up to 20 tiles away.',
  'Dark Tosser': 'Throws creatures up to 5 tiles away.',
  'Dark Hurler': 'Throws creatures up to 10 tiles away.',
  'Dark Chucker': 'Throws creatures up to 15 tiles away.',
  'Dark Ace': 'Throws creatures up to 20 tiles away.',
  'Curse Girl': 'Curses or seals 1 item.',
  'Cursister': 'Curses or seals 1 item.',
  'Curspinster': 'Curses or seals 2 items.',
  'Cursenior': 'Curses or seals 2 items.',
  'Foul Curse Girl': 'Curses or seals 1 item.',
  'Foul Cursister': 'Curses or seals 1 item.',
  'Foul Curspinster': 'Curses or seals 2 items.',
  'Foul Cursenior': 'Curses or seals 2 items.',
  'Fearabbit': 'Attracts creatures in the room to itself',
  'Scarabbit': 'Attracts creatures in the room to itself',
  'Horrabbit': 'Attracts creatures on the floor to itself',
  'Terrabbit': 'Attracts creatures on the floor to itself',
  'Dark Fearabbit': 'Attracts creatures in the room to itself',
  'Dark Scarabbit': 'Attracts creatures in the room to itself',
  'Dark Horrabbit': 'Attracts creatures on the floor to itself',
  'Dark Terrabbit': 'Attracts creatures on the floor to itself',
  'Gyaza': 'Converts non-direct attack effects into 2 damage.',
  'Death Gyaza': 'Converts non-direct attack effects into 2 damage.',
  'Hell Gyaza': 'Converts non-direct attack effects into 2 damage.',
  'Doom Gyaza': 'Converts non-direct attack effects into 2 damage.',
  'Evil Gyaza': 'Converts non-direct attack effects into 2 damage.',
  'Evil Death Gyaza': 'Converts non-direct attack effects into 2 damage.',
  'Evil Hell Gyaza': 'Converts non-direct attack effects into 2 damage.',
  'Evil Doom Gyaza': 'Converts non-direct attack effects into 2 damage.',
  'Pumphantasm': 'Moves through walls, unpredictable movement.',
  'Pumphantom': 'Moves through walls, unpredictable movement.',
  'Pumpanshee': 'Moves through walls, unpredictable movement.',
  'Pumptergeist': 'Moves through walls, unpredictable movement.',
  'Vile Pumphantasm': 'Moves through walls, unpredictable movement.',
  'Vile Pumphantom': 'Moves through walls, unpredictable movement.',
  'Vile Pumpanshee': 'Moves through walls, unpredictable movement.',
  'Vile Pumptergeist': 'Moves through walls, unpredictable movement.',
  'Floaty': 'Swift 1, always generated in a group of 3.',
  'Poofy': 'Swift 1, always generated in a group of 3.',
  'Jouncy': 'Swift 1, always generated in a group of 3.',
  'Bouncy': 'Swift 1, always generated in a group of 3.',
  'Evil Floaty': 'Swift 1, always generated in a group of 3.',
  'Evil Poofy': 'Swift 1, always generated in a group of 3.',
  'Evil Jouncy': 'Swift 1, always generated in a group of 3.',
  'Evil Bouncy': 'Swift 1, always generated in a group of 3.',
  "N'dubba": 'Disguised as an item, attacks if you pick it up.',
  "N'twyn": "Doesn't reveal itself until you use the item.",
  "N'mach": "Doesn't reveal itself until you use the item.",
  "N'dup": "Random ability from N'dubba, N'mach, or N'dup.",
  "Dark N'dubba": 'Disguised as an item, attacks if you pick it up.',
  "Dark N'twyn": "Doesn't reveal itself until you use the item.",
  "Dark N'mach": "Doesn't reveal itself until you use the item.",
  "Dark N'dup": "Random ability from N'dubba, N'mach, or N'dup.",
  'Mixer': 'Eats up to 2 items and synthesizes them.',
  'Mixermon': 'Eats up to 3 items and synthesizes them.',
  'Mixergon': 'Eats up to 4 items and synthesizes them.',
  'Mixerdon': 'Eats up to 5 items and synthesizes them.',
  'Dark Mixer': 'Eats up to 2 items and synthesizes them.',
  'Dark Mixermon': 'Eats up to 3 items and synthesizes them.',
  'Dark Mixergon': 'Eats up to 4 items and synthesizes them.',
  'Dark Mixerdon': 'Eats up to 5 items and synthesizes them.',
  'Scorpion': 'Decreases strength by 1.',
  'VeniScorp': 'Decreases strength by 2.',
  'StunScorp': 'Decreases max strength by 1.',
  'BlightScorp': 'Decreases max strength by 2.',
  'Dark Scorpion': 'Decreases strength by 2.',
  'Dark VeniScorp': 'Decreases strength by 3.',
  'Dark StunScorp': 'Decreases max strength by 2.',
  'Dark BlightScorp': 'Decreases max strength by 3.',
  'Mutaikon': 'Throws Poison Grass up to 2 tiles ahead.',
  'Dazikon': 'Throws Confusion Grass in a 2 tile radius.',
  'Dozikon': 'Throws Sleepy Grass in a 3 tile radius.',
  'Mesmerikon': 'Throws Rage Grass in a 5 tile radius.',
  'Dark Mutaikon': 'Throws Poison Grass up to 2 tiles ahead.',
  'Dark Dazikon': 'Throws Confusion Grass in a 2 tile radius.',
  'Dark Dozikon': 'Throws Sleepy Grass in a 3 tile radius.',
  'Dark Mesmerikon': 'Throws Rage Grass in a 5 tile radius.',
  'Naptapir': "Inflicts Asleep when you're next to it.",
  'Snooztapir': "Inflicts Asleep when you're next to it.",
  'Doztapir': "Inflicts Asleep when you're next to it.",
  'Comatapir': "Inflicts Asleep when you're next to it.",
  'Dark Naptapir': "Inflicts Asleep when you're next to it.",
  'Dark Snooztapir': "Inflicts Asleep when you're next to it.",
  'Dark Doztapir': "Inflicts Asleep when you're next to it.",
  'Dark Comatapir': "Inflicts Asleep when you're next to it.",
  'Swordsman': 'Disarms your shield.',
  'Fencer': 'Disarms your weapon or shield.',
  'Sensei': 'Disarms your weapon, shield, or bracelet.',
  'Swordmaster': 'Disarms your weapon, shield, or bracelet.',
  'Evil Swordsman': 'Disarms your shield.',
  'Evil Fencer': 'Disarms your weapon or shield.',
  'Evil Sensei': 'Disarms your weapon, shield, or bracelet.',
  'Evil Swordmaster': 'Disarms your weapon, shield, or bracelet.',
  'Mudkin': 'Lowers weapon or shield upgrade value by 1.',
  'Muddy': 'Lowers weapon or shield upgrade value by 2.',
  'Mudster': 'Lowers weapon and shield upgrade values by 1.<br>Erases a weapon or shield rune.',
  'Mudder': 'Lowers weapon and shield upgrade values by 2.<br>Erases a weapon or shield rune.<br>Invisible on water tiles.',
  'Shady Mudkin': 'Lowers weapon or shield upgrade value by 2.',
  'Shady Muddy': 'Lowers weapon or shield upgrade value by 4.',
  'Shady Mudster': 'Lowers weapon and shield upgrade values by 2.<br>Erases a weapon or shield rune.',
  'Shady Mudder': 'Lowers weapon and shield upgrade values by 3.<br>Erases a weapon or shield rune.<br>Invisible on water tiles.',
  'Polygon Spinna': 'Lowers max HP by 1, or max fullness by 3.',
  'Polygon Shaka': 'Lowers max HP by 2, or max fullness by 5.',
  'Polygon Singa': 'Lowers max HP by 3, or max fullness by 7.',
  'Polygon Stunna': 'Lowers max HP by 5, or max fullness by 10.',
  'Evil PolySpinna': 'Lowers max HP by 2, or max fullness by 5.',
  'Evil PolyShaka': 'Lowers max HP by 3, or max fullness by 7.',
  'Evil PolySinga': 'Lowers max HP by 4, or max fullness by 10.',
  'Evil PolyStunna': 'Lowers max HP by 6, or max fullness by 15.',
  'Metalhead': 'Hits targets 2 tiles away, charges strength.',
  'Ironhead': 'Hits targets 2 tiles away, charges strength.',
  'Steelhead': 'Hits targets 2 tiles away, charges strength.',
  'Doomhead': 'Hits targets 2 tiles away, charges strength.',
  'Dark Metalhead': 'Hits targets 2 tiles away, charges strength.',
  'Dark Ironhead': 'Hits targets 2 tiles away, charges strength.',
  'Dark Steelhead': 'Hits targets 2 tiles away, charges strength.',
  'Dark Doomhead': 'Hits targets 2 tiles away, charges strength.',
  'Cheer-Ham': 'Raises attack by 1 stage, grants Enduring.',
  'Go-Ham!': 'Raises attack by 2 stages, grants Enduring.',
  'Rally Ham': 'Raises attack and defense by 1 stage, grants Enduring.',
  'Spirit Ham': 'Raises attack and defense by 2 stages, grants Enduring.',
  'Mean Cheer-Ham': 'Raises attack by 1 stage, grants Enduring.',
  'Mean Go-Ham!': 'Raises attack by 2 stages, grants Enduring.',
  'Mean Rally Ham': 'Raises attack and defense by 1 stage, grants Enduring.',
  'Mean Spirit Ham': 'Raises attack and defense by 2 stages, grants Enduring.',
  'Kid Squid': 'Inflicts Blind 1 tile in front.',
  'Squidfficial': 'Inflicts Blind in a 1 tile radius.',
  'King Squid': 'Inflicts Blind to all targets in the room.',
  'Squidperor': 'Inflicts Blind to all targets in the room.',
  'Evil Kid Squid': 'Inflicts Blind 1 tile in front.',
  'Evil Squidfficial': 'Inflicts Blind in a 1 tile radius.',
  'Evil King Squid': 'Inflicts Blind to all targets in the room.',
  'Evil Squidperor': 'Inflicts Blind to all targets in the room.',
  'Foly': 'Swift 1, <span class="warning_text">red</span> = reflect attack, <span class="green_text">green</span> = heal 100 HP,<br><span class="important_text">blue</span> = 15 damage to the room, <span class="purple_text">purple</span> = inflicts an ailment.',
  'Dark Foly': 'Swift 1, <span class="warning_text">red</span> = reflect attack, <span class="green_text">green</span> = heal 100 HP,<br><span class="important_text">blue</span> = 15 damage to the room, <span class="purple_text">purple</span> = inflicts an ailment.',
  'Bored Kappa': 'Throws items in a 3 tile radius, always misses.',
  'Kappa Pest': 'Throws items in a 5 tile radius.',
  'Vexing Kappa': 'Throws items in a 10 tile radius.',
  'Kappa Troll': 'Throws items from anywhere on the floor.',
  'Dark Bored Kappa': 'Throws items in a 3 tile radius, always misses.',
  'Dark Kappa Pest': 'Throws items in a 5 tile radius.',
  'Dark Vexing Kappa': 'Throws items in a 10 tile radius.',
  'Dark Kappa Troll': 'Throws items from anywhere on the floor.',
  'Hopodile': 'Chess knight movement, 10 damage body slam.',
  'Hipadile': 'Chess knight movement, 20 damage body slam.',
  'Oingodile': 'Chess knight movement, 30 damage body slam.',
  'Boingodile': 'Chess knight movement, 40 damage body slam.',
  'Evil Hopodile': 'Chess knight movement, 15 damage body slam.',
  'Evil Hipadile': 'Chess knight movement, 25 damage body slam.',
  'Evil Oingodile': 'Chess knight movement, 35 damage body slam.',
  'Evil Boingodile': 'Chess knight movement, 45 damage body slam.',
  'Flamebird': "Heals a monster's HP by 30.",
  'Sparkbird': "Heals a monster's HP by 60.",
  'Flarebird': "Heals 30 HP to all monsters in a 1 tile radius.",
  'Blazebird': "Heals 60 HP to all monsters in a 1 tile radius.",
  'Dark Flamebird': "Heals a monster's HP by 40.",
  'Dark Sparkbird': "Heals a monster's HP by 70.",
  'Dark Flarebird': "Heals 40 HP to all monsters in a 1 tile radius.",
  'Dark Blazebird': "Heals 70 HP to all monsters in a 1 tile radius.",
  'Yanpii': 'Headbutts, dealing 10 damage and knockback.',
  'Sr. Yanpii': 'Headbutts, dealing 20 damage and knockback.',
  'Lt. Yanpii': 'Headbutts, dealing 30 damage and knockback.',
  'Boss Yanpii': 'Headbutts, dealing 40 damage and knockback.',
  'Sinful Yanpii': 'Headbutts, dealing 10 damage and knockback.',
  'Sinful Sr. Yanpii': 'Headbutts, dealing 20 damage and knockback.',
  'Sinful Lt. Yanpii': 'Headbutts, dealing 30 damage and knockback.',
  'Sinful Boss Yanpii': 'Headbutts, dealing 40 damage and knockback.',
  'Scoopie': 'Throws dirt into a pot 1 tile in front.',
  'Spadie': 'Throws dirt into a pot 1 tile in front.',
  'Trowelie': 'Throws dirt into a pot, range of 4 tiles.',
  'Shovelie': 'Throws dirt into a pot, range of 6 tiles.',
  'Wicked Scoopie': 'Throws dirt into a pot 1 tile in front.',
  'Wicked Spadie': 'Throws dirt into a pot 1 tile in front.',
  'Wicked Trowelie': 'Throws dirt into a pot, range of 5 tiles.',
  'Wicked Shovelie': 'Throws dirt into a pot, range of 5 tiles.',
  'Zalokleft': 'Steals an item and warps away.',
  'Green Zalokleft': 'Steals an item and warps away.',
  'Iron Zalokleft': 'Steals an item and warps away.',
  'Zalokleftis King': 'Steals an item and vanishes from the floor.',
  'Bad Zalokleft': 'Steals an item and warps away.',
  'Bad G. Zalokleft': 'Steals an item and warps away.',
  'Bad I. Zalokleft': 'Steals an item and warps away.',
  'Bad Zalokleft King': 'Steals an item and vanishes from the floor.',
  'Gyadon': "Lowers a staff's use count to 0.",
  'Gyairas': 'Turns a scroll or talisman into a Piece of Paper.',
  'Gyandora': "Reduces a pot's size to 0.",
  'Gyandoron': 'Pecks staves, scrolls, talismans, and pots.<br>Also pecks weapons or shields, erasing a rune.',
  'Violent Gyadon': "Lowers a staff's use count to 0.",
  'Violent Gyairas': 'Turns a scroll or talisman into a Piece of Paper.',
  'Violent Gyandora': "Reduces a pot's size to 0.",
  'Violent Gyandoron': 'Pecks staves, scrolls, talismans, and pots.<br>Also pecks weapons or shields, erasing a rune.',
  'Gazer': 'Inflicts Hypnotized 1 tile in front.',
  'Super Gazer': 'Inflicts Hypnotized 1 tile in front.',
  'Hyper Gazer': 'Inflicts Hypnotized 1 tile in front.',
  'Ultra Gazer': 'Inflicts Hypnotized in the room, drops 5000G.',
  'Evil Gazer': 'Inflicts Hypnotized 1 tile in front.',
  'Evil Super Gazer': 'Inflicts Hypnotized 1 tile in front.',
  'Evil Hyper Gazer': 'Inflicts Hypnotized 1 tile in front.',
  'Evil Ultra Gazer': 'Inflicts Hypnotized in the room, drops 5000G.',
  'Zapdon': 'Slow, 25 damage counter after 3 hits.',
  'Huistdon': 'Slow, 30 damage counter after 3 hits.',
  'Bunchukdon': 'Slow, 35 damage counter after 3 hits.',
  'Zotdon': 'Slow, 40 damage counter after 3 hits.',
  'Dark Zapdon': 'Slow, 40 damage counter after 3 hits.',
  'Dark Huistdon': 'Slow, 50 damage counter after 3 hits.',
  'Dark Bunchukdon': 'Slow, 60 damage counter after 3 hits.',
  'Dark Zotdon': 'Slow, 70 damage counter after 3 hits.',
  'Dragon': '20 damage fire in a straight line.',
  'Sky Dragon': '20 damage fire from anywhere in the room.',
  'Archdragon': '30 damage fire from anywhere on the floor.',
  'Abyssal Dragon': '40 damage fire from anywhere on the floor.',
  'Evil Dragon': '50 damage fire in a straight line.',
  'Evil Sky Dragon': '50 damage fire from anywhere in the room.',
  'Evil Archdragon': '60 damage fire from anywhere on the floor.',
  'Evil Abyss Dragon': '70 damage fire from anywhere on the floor.',
  'DJ Mage': 'Warp, knockback, swap places, or swift by 1 stage.',
  'MC Mage': 'Confused, Blind, transient effect, or 20 damage.',
  'MC Wizard': 'Berserk, Sealed, Paralyzed, Cloned, or level down by 1.',
  'MC Sorceror': 'Onigiri, Empathy, Slow, lower HP to 1/4, level down by 3.',
  'Dark DJ Mage': 'Warp, knockback, swap places, or swift by 1 stage.',
  'Dark MC Mage': 'Confused, Blind, transient effect, or 20 damage.',
  'Dark MC Wizard': 'Berserk, Sealed, Paralyzed, Cloned, or level down by 1.',
  'Dark MC Sorceror': 'Onigiri, Empathy, Slow, lower HP to 1/4, level down by 3.',
  'Porky': 'Throws 20 damage Porky Rocks, range of 2 tiles.',
  'Porko': 'Throws 20 damage Porky Rocks, range of 4 tiles.',
  'Porkon': 'Throws 20 damage Porky Rocks, range of 6 tiles.',
  'Porgon': 'Throws 20 damage Porky Rocks, range of 10 tiles.',
  'Sinister Porky': 'Throws 20 damage Porky Rock, range of 2 tiles.',
  'Sinister Porko': 'Throws 20 damage Porky Rock, range of 4 tiles.',
  'Sinister Porkon': 'Throws 20 damage Porky Rock, range of 6 tiles.',
  'Sinister Porgon': 'Throws 20 damage Porky Rock, range of 10 tiles.',
  'Boy Cart': 'Swift 1, shoots Wood Arrows.',
  'Cross Cart': 'Swift 1, shoots Iron Arrows.',
  'Strong Cart': 'Swift 1, shoots Knockback Arrows.',
  'Pierce Cart': 'Swift 1, shoots Silver Arrows.',
  'Dark Boy Cart': 'Swift 1, shoots Wood Arrows.',
  'Dark Cross Cart': 'Swift 1, shoots Iron Arrows.',
  'Dark Strong Cart': 'Swift 1, shoots Knockback Arrows.',
  'Dark Pierce Cart': 'Swift 1, shoots Silver Arrows.',
  'Pop Tank': 'Slow, fires 20 damage cannonballs.',
  'Grampa Tank': 'Fires 30 damage cannonballs.',
  'Ornery Tank': 'Swift 1, fires 40 damage cannonballs.',
  'Cranky Tank': 'Swift 2, fires 50 damage cannonballs.',
  'Dark Pop Tank': 'Slow, fires 30 damage cannonballs.',
  'Dark Grampa Tank': 'Fires 40 damage cannonballs.',
  'Dark Ornery Tank': 'Swift 1, fires 50 damage cannonballs.',
  'Dark Cranky Tank': 'Swift 2, fires 60 damage cannonballs.',
  'Absorbiphant': 'Absorbs status. (Heal HP, boost attack by 1 stage)',
  'Digestiphant': 'Absorbs status. (Heal HP, boost attack by 2 stages)',
  'Spongiderm': 'Absorbs status. (Heal HP, boost attack & defense by 1 stage)',
  'Osmammoth': 'Absorbs status. (Heal HP, boost attack & defense by 2 stages)',
  'Dark Absorbiphant': 'Absorbs status. (Heal HP, boost attack by 1 stage)',
  'Dark Digestiphant': 'Absorbs status. (Heal HP, boost attack by 2 stages)',
  'Dark Spongiderm': 'Absorbs status. (Heal HP, boost attack & defense by 1 stage)',
  'Dark Osmammoth': 'Absorbs status. (Heal HP, boost attack & defense by 2 stages)',
  'Punisher': 'Chance to deal a critical hit.',
  'Debaser': 'Chance to deal a critical hit.',
  'Ruiner': 'Chance to deal a critical hit.',
  'Despoiler': 'Chance to deal a critical hit.',
  "Hell's Punisher": 'Chance to deal a critical hit.',
  "Hell's Debaser": 'Chance to deal a critical hit.',
  "Hell's Ruiner": 'Chance to deal a critical hit.',
  "Hell's Despoiler": 'Chance to deal a critical hit.',
  'Firepuff': '10 damage fire 1 tile in front.',
  'Flamepuff': '20 damage fire 1 tile in front.',
  'Blazepuff': '30 damage fire 1 tile in front.',
  'Pyrepuff': '40 damage fire 1 tile in front.',
  'Evil Firepuff': '20 damage fire 1 tile in front.',
  'Evil Flamepuff': '40 damage fire 1 tile in front.',
  'Evil Blazepuff': '60 damage fire 1 tile in front.',
  'Evil Pyrepuff': '80 damage fire 1 tile in front.',
  'Crow Tengu': 'Disguises itself as a different monster.',
  'Falcon Tengu': 'Disguises itself as a different monster.',
  'Eagle Tengu': 'Disguises itself as a different monster.',
  'Phoenix Tengu': 'Disguises itself as a different monster.',
  'Bad Crow Tengu': 'Disguises itself as a different monster.',
  'Bad Falcon Tengu': 'Disguises itself as a different monster.',
  'Bad Eagle Tengu': 'Disguises itself as a different monster.',
  'Bad Phoenix Tengu': 'Disguises itself as a different monster.',
  'FO-Uβ': 'Swift 2, damage deals 1 HP, drops 1~3 Life Grass.<br>Chance to summon a Myriman when hit.',
  'FO-U': 'Swift 2, damage deals 1 HP, drops 1~3 Cheery Grass.<br>Chance to summon a Billman when hit.',
  'FO-UZ': 'Swift 2, damage deals 1 HP, drops 1~3 Strength Grass.<br>Chance to summon a Trillman when hit.',
  'FO-UZZ': 'Swift 2, damage deals 1 HP, drops 1~3 Revival Grass.<br>Chance to summon a Googoman when hit.',
  'εFO-Uβ': 'Swift 2, damage deals 1 HP, drops 1~3 Life Grass.<br>Chance to summon a Myriman when hit.',
  'εFI-U': 'Swift 2, damage deals 1 HP, drops 1~3 Cheery Grass.<br>Chance to summon a Billman when hit.',
  'εFO-UZ': 'Swift 2, damage deals 1 HP, drops 1~3 Strength Grass.<br>Chance to summon a Trillman when hit.',
  'εFO-UZZ': 'Swift 2, damage deals 1 HP, drops 1~3 Revival Grass.<br>Chance to summon a Googoman when hit.',
  'Myriman': 'Inflicts Grassnesia.',
  'Billman': 'Inflicts Scrollnesia.',
  'Trillman': 'Inflicts Staffnesia.',
  'Googoman': 'Inflicts Potnesia.',
  'Dark Myriman': 'Inflicts Grassnesia.',
  'Dark Billman': 'Inflicts Scrollnesia.',
  'Dark Trillman': 'Inflicts Staffnesia.',
  'Dark Googoman': 'Inflicts Potnesia.',
  'Moseal': '10 damage tackle from up to 10 tiles away.',
  'Momoseal': '20 damage tackle from up to 15 tiles away.',
  'Momomoseal': '30 damage tackle from up to 20 tiles away.',
  'Momomomoseal': '40 damage tackle from up to 25 tiles away.',
  'Bad Moseal': '15 damage tackle.',
  'Bad Momoseal': '25 damage tackle.',
  'Bad Momomoseal': '35 damage tackle.',
  'Bad Momomomoseal': '45 damage tackle.',
  'Kumonigiri': 'Chance to drop an Onigiri.',
  'Pandanigiri': 'Chance to drop an Onigiri.',
  'Onigirizzly': 'Chance to drop an Onigiri.',
  'Kodionigiri': 'Chance to drop an Onigiri.',
  'Dark Kumonigiri': 'Chance to drop an Onigiri.',
  'Dark Pandanigiri': 'Chance to drop an Onigiri.',
  'Dark Onigirizzly': 'Chance to drop an Onigiri.',
  'Dark Kodionigiri': 'Chance to drop an Onigiri.',
  'Nashagga': 'Attacks 2 times in a single turn.',
  'Lashagga': 'Attacks 3 times in a single turn.',
  'Bashagga': 'Attacks 4 times in a single turn.',
  'Filthy Nashagga': 'Attacks 2 times in a single turn.',
  'Filthy Lashagga': 'Attacks 3 times in a single turn.',
  'Filthy Bashagga': 'Attacks 4 times in a single turn.',
  'Explochin': 'Stops moving after it loses 35 or more HP.<br>Explodes after it loses 50 or more HP.',
  'Concusschin': 'Stops moving after it loses 40 or more HP.<br>Explodes after it loses 58 or more HP.',
  'Fulminachin': 'Stops moving after it loses 46 or more HP.<br>Explodes after it loses 67 or more HP.',
  'Detonachin': 'Stops moving after it loses 53 or more HP.<br>Explodes after it loses 77 or more HP.',
  'Evil Explochin': 'Stops moving after it loses a certain amount of HP.<br>Explodes after it loses even more HP.',
  'Evil Concusschin': 'Stops moving after it loses a certain amount of HP.<br>Explodes after it loses even more HP.',
  'Evil Fulminachin': 'Stops moving after it loses a certain amount of HP.<br>Explodes after it loses even more HP.',
  'Evil Detonachin': 'Stops moving after it loses a certain amount of HP.<br>Explodes after it loses even more HP.',
  'Chow': 'Swift 1, always drops an item.',
  'Snacky': 'Swift 1, always drops an item. (S column)',
  'Munchy': 'Swift 1, always drops an item. (S column)',
  'Mealy': 'Swift 1, always drops an item. (M column)',
  'Plump Chow': 'Swift 1, always drops an item.',
  'Plump Snacky': 'Swift 1, always drops an item. (S column)',
  'Plump Munchy': 'Swift 1, always drops an item. (S column)',
  'Plump Mealy': 'Swift 1, always drops an item. (M column)',
  'Field Knave': 'Throws Weeds, turns floor items into Weeds.',
  'Pot Knave': 'Throws Weeds into pots, turns items into Weeds.',
  'Item Knave': 'Throws Weeds which knocks an item away,<br>turns floor items into Weeds.',
  'Knave King': 'Throws Weeds which knocks an item away,<br>turns floor and inventory items into Weeds.',
  'Dark Field Knave': 'Throws Weeds, turns floor items into Weeds.',
  'Dark Pot Knave': 'Throws Weeds into pots, turns items into Weeds.',
  'Dark Item Knave': 'Throws Weeds which knocks an item away,<br>turns floor items into Weeds.',
  'Dark Knave King': 'Throws Weeds which knocks an item away,<br>turns floor and inventory items into Weeds.',
  'Maneater': 'Speed changes to Swift 1 when it sees Shiren,<br>chance to inflict Paralyzed when it roars.',
  'Villeater': 'Speed changes to Swift 1 when it sees Shiren,<br>chance to inflict Paralyzed when it roars.',
  'Mounteater': 'Speed changes to Swift 1 when it sees Shiren,<br>chance to inflict Paralyzed when it roars.',
  'Isleater': 'Speed changes to Swift 1 when it sees Shiren,<br>chance to inflict Paralyzed when it roars.',
  'Dark Maneater': 'Speed changes to Swift 1 when it sees Shiren,<br>chance to inflict Paralyzed when it roars.',
  'Dark Villeater': 'Speed changes to Swift 1 when it sees Shiren,<br>chance to inflict Paralyzed when it roars.',
  'Dark Mounteater': 'Speed changes to Swift 1 when it sees Shiren,<br>chance to inflict Paralyzed when it roars.',
  'Dark Isleater': 'Speed changes to Swift 1 when it sees Shiren,<br>chance to inflict Paralyzed when it roars.'
}.with_indifferent_access

# --- main ---
html = []
time_of_day_class = 'highlight_blue'
file = File.read('well_monsters_night')

# headers
html.push('          <table class="monsters_table">
            <tr>
              <th>F</th>
              <th>Name</th>
              <th>HP</th>
              <th>Atk</th>
              <th>Def</th>
              <th>Exp</th>
              <th>Skill</th>
              <th>Effective<br>Rune / Item</th>
              <th>Notes</th>
            </tr>')

file.each_line do |line|
  regex = /(\S+)/
  words = line.scan(regex)

  jp_name = words[0][0]
  # example: change "1-2/3-4/5" to "1-2,<br>3-4,<br>5"
  floors = words[1][0].gsub(/\//, ",<br>")
  hp = words[2][0]
  attack = words[3][0]
  defense = words[4][0]
  exp = words[5][0]
  skill = words[6][0]

  html.push('            <tr>')
  html.push("              <td>#{floors}</td>")
  html.push("              <td class=\"#{time_of_day_class}\">#{monsters_en[jp_name] || 'MISSING_NAME'}</td>")
  html.push("              <td>#{hp}</td>")
  html.push("              <td>#{attack}</td>")
  html.push("              <td>#{defense}</td>")
  html.push("              <td>#{exp}</td>")
  html.push("              <td>#{skill}</td>")
  html.push("              <td>#{effective[monsters_en[jp_name]] || '-'}</td>")
  html.push("              <td>#{notes[monsters_en[jp_name]] || '-'}</td>")
  html.push('            </tr>')
end

html.push('          </table>')

File.write('output.html', html.join("\n"))
